#define VERSION_OF_CONFIG "0.1.0"
#define NAME_OF_CONFIG_FILE "config.json"
#define NAME_OF_ANSWERS_FILE "answers.json"
#define NAME_OF_REQUESTS_FILE "requests.json"
#define IS_MISSING_MSG(FILENAME) FILENAME" file is missing."
#define IS_EMPTY_MSG(FILENAME) FILENAME" file is empty."
#define IS_INCORRECT_VERSION_MSG(FILENAME) FILENAME" file has incorrect file version."
#define IS_NOT_AVAILABLE_MSG(FILENAME) FILENAME" file is not available."
